"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.container = void 0;
require("reflect-metadata");
const inversify_1 = require("inversify");
const types_1 = require("./types");
const DefaultGrayscaleLayout_1 = require("../layouts/DefaultGrayscaleLayout");
const InvoiceGenerator_1 = require("../core/InvoiceGenerator");
const container = new inversify_1.Container();
exports.container = container;
container.bind(types_1.TYPES.LayoutStrategy).to(DefaultGrayscaleLayout_1.DefaultGrayscaleLayout);
container.bind(types_1.TYPES.InvoiceGenerator).to(InvoiceGenerator_1.InvoiceGenerator);
